---
# DHCP configuration
apiVersion: pantheon.tech/v1
kind: CNFConfiguration
metadata:
  name: client
spec:
  microservice: client
  configItems:
    - module: cnf.nsm
      version: v1
      type: client
      data: |-
        name: access-to-cnf-network
        network_service: cnf-nat-example
        outgoing_labels:
          - key: app
            value: client
        interface_name: tap0
        interface_type: KERNEL_INTERFACE
        ipAddresses:
          - "192.168.100.10/24"
    - module: linux.l3
      type: route
      data: |-
        outgoing_interface: tap0
        scope: GLOBAL
        dst_network: 80.80.80.0/24
        gw_addr: 192.168.100.1

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    cnf: client
spec:
  containers:
    - name: client
      image: pantheontech/nsm-agent-linux:v3.1.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
        - name: ETCD_CONFIG
          value: "/etc/etcd/etcd.conf"
        - name: MICROSERVICE_LABEL
          value: "client"
      resources:
        limits:
          networkservicemesh.io/socket: 1
      volumeMounts:
        - name: etcd-cfg
          mountPath: /etc/etcd
  volumes:
    - name: etcd-cfg
      configMap:
        name: cnf-etcd-cfg
