---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: cnf-nat-example
spec:
  payload: IP
  matches:
    # connect client to the (local side of) cnf-nat44
    - match:
      sourceSelector:
        app: client
      route:
        - destination:
          destinationSelector:
            app: nat44
    # connect the (external side of) cnf-nat44 to the webserver
    - match:
      sourceSelector:
        app: nat44
      route:
        - destination:
          destinationSelector:
            app: webserver