---
apiVersion: pantheon.tech/v1
kind: CNFConfiguration
metadata:
  name: webserver
spec:
  microservice: webserver
  configItems:
    - module: cnf.nsm
      version: v1
      type: endpoint
      data: |-
        network_service: cnf-nat-example
        advertised_labels:
          - key: app
            value: webserver
        interface_name_prefix: memif # full name: memif0
        interface_type: MEM_INTERFACE
        single_client: true
        ipAddresses:
          - "80.80.80.80/24"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpp-startup-cfg
data:
  vpp.conf: |
    unix {
        nodaemon
        cli-listen /run/vpp/cli.sock
        cli-no-pager
        log /tmp/vpp.log
        coredump-size unlimited
        full-coredump
        poll-sleep-usec 50
        startup-config /etc/vpp/cli-config.txt
    }
    plugins {
        plugin dpdk_plugin.so {
            disable
        }
    }
    api-trace {
        on
    }
    socksvr {
    	default
    }
    statseg {
    	default
    	per-node-counters on
    }
    nat {
        endpoint-dependent
        translation hash buckets 1048576
        translation hash memory 268435456
        user hash buckets 1024
        max translations per user 10000
    }
  cli-config.txt: |
    comment { start HTTP server }
    test http server

---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  containers:
    - name: webserver
      image: pantheontech/nsm-agent-vpp:v3.1.0
      env:
        - name: ETCD_CONFIG
          value: "/etc/etcd/etcd.conf"
        - name: MICROSERVICE_LABEL
          value: "webserver"
      resources:
        limits:
          networkservicemesh.io/socket: 1
      volumeMounts:
        - name: etcd-cfg
          mountPath: /etc/etcd
        - name: vpp-startup-cfg
          mountPath: /etc/vpp
  volumes:
    - name: etcd-cfg
      configMap:
        name: cnf-etcd-cfg
    - name: vpp-startup-cfg
      configMap:
        name: vpp-startup-cfg
