---
apiVersion: pantheon.tech/v1
kind: CNFConfiguration
metadata:
  name: vpp-webserver
spec:
  microservice: vpp-webserver
  configItems:
    - module: cnf.nsm
      version: v1
      type: endpoint
      data: |-
        name: access-to-webserver-client
        network_service: cnf-nat-example
        advertised_labels:
          - key: app
            value: webserver
        single_client: true
        interface_name_prefix: client
        interface_type: MEM_INTERFACE
        ipAddresses:
          - "80.80.80.101/30"

---
apiVersion: v1
kind: Pod
metadata:
  name: vpp-webserver
  labels:
    app: vpp-webserver
spec:
  containers:
    - name: vpp-webserver
      image: pantheontech/nsm-agent-vpp:v3.0.0
      env:
        - name: ETCD_CONFIG
          value: "/etc/etcd/etcd.conf"
        - name: MICROSERVICE_LABEL
          value: "vpp-webserver"
      resources:
        limits:
          networkservicemesh.io/socket: 1
      volumeMounts:
        - name: etcd-cfg
          mountPath: /etc/etcd
  volumes:
    - name: etcd-cfg
      configMap:
        name: cnf-etcd-cfg